from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

document = Document()


# profile picture
document.add_picture(
    'stockphotoprofilepic.jpg',
    width=Inches(2.0))

# name, phone number, email
name = input('Name: ')
speak('Hello' + name)
phone_number = input('Phone number: ')
email = input('Email: ')

document.add_paragraph(name + '|'+ phone_number + '|' + email )

# profile
document.add_heading('Profile')
profile = input(
    'Profile summary: ')
document.add_paragraph(profile)

# work experience
document.add_heading('Work Experience')
p = document.add_paragraph()

company = input('Enter company: ')
from_date = input('From Date: ')
to_date = input('To Date: ')

p.add_run(company + ' ').bold = True
p.add_run(from_date + '-' + to_date + '\n').italic = True

experience_details = input(
    'Describe your experience at ' + company + ': ')
p.add_run(experience_details)

# more experiences
while True:
    has_more_experiences = input(
        'More experiences? Y/N: ')
    if has_more_experiences == 'Y':
        p = document.add_paragraph()

        company = input('Enter company: ')
        from_date = input('From Date: ')
        to_date = input('To Date: ')

        p.add_run(company + ' ').bold = True
        p.add_run(from_date + '-' + to_date + '\n').italic = True

        experience_details = input(
            'Describe your experience at ' + company + ': ')
        p.add_run(experience_details)
    else:
        break

#skills
document.add_heading('Skills')
skill_details = input('List a skill: ')
p = document.add_paragraph(skill_details)
p.style = 'List Bullet'

# more skills
while True:
    has_more_skills = input('More skills? Y/N: ')

    if has_more_skills.lower() == 'y':
        skills = input('List a skill: ')
        
        p = document.add_paragraph(skills)
        p.style = 'List Bullet'

    else:
        break


#footer
section = document.sections[0]
footer = section.footer 
p = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph
p.text = 'CV generated by BethanyJ'


document.save('cv.docx')
